timeout: 60
led_gpio_number: 21
shutter_speed: 6000000
camera_wait_time: 30
canny_threshold1: 80
canny_threshold2: 100
blur_ksize_width: 5
blur_ksize_height: 5

bounding_box_same_y_threshold: 15
bounding_box_same_height_threshold: 5
image_rotation: 179.2

ravendb_pem_file: raven_cert/PEM/free.chsauer.client.certificate.pem
ravendb_url: https://a.free.chsauer.ravendb.cloud
ravendb_db: readings
image_retaining_hours: 1

positions:
  - x: 358
    y: 471
    w: 20
    h: 40

  - x: 413
    y: 471
    w: 20
    h: 40

  - x: 470
    y: 471
    w: 20
    h: 40

  - x: 526
    y: 471
    w: 20
    h: 40

  - x: 583
    y: 471
    w: 20
    h: 40

  - x: 642
    y: 471
    w: 20
    h: 40

  - x: 703
    y: 471
    w: 20
    h: 40