ravendb_pem_file: raven_cert/PEM/free.chsauer.client.certificate.pem
ravendb_url: https://a.free.chsauer.ravendb.cloud
ravendb_db: readings
ravendb_time_series_name: "gas (reed)"

debounce_seconds: 5
timeout_seconds: 1

gpio_bcm_nr: 21